src/SFA.DAS.ASK.Web/ViewModels/Feedback/ConfirmDetailsViewModel.cs
using SFA.DAS.ASK.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SFA.DAS.ASK.Web.ViewModels.Feedback
{
    public class ConfirmDetailsViewModel
    {
        public Guid FeedbackId { get; set; }
        public string EstablishmentName { get; set; }
        public string EstablishmentAddress { get; set; }
        public string YourFullName { get; set; }
        public string DateOfActivity { get; set; }
        public List<VisitActivity> Activities { get; set; }
        public string IncorrectDetailsComments { get; set; }

        public ConfirmDetailsViewModel(VisitFeedback feedback)
        {
            FeedbackId = feedback.Id;

            var visit = feedback.Visit;

            EstablishmentName = visit.SupportRequest.Organisation.OrganisationName;
            
            YourFullName = $"{visit.OrganisationContact.FirstName} {visit.OrganisationContact.LastName}";
            DateOfActivity = visit.VisitDate.ToString("dd/MM/yyyy");
            Activities = visit.Activities;
            IncorrectDetailsComments = feedback.IncorrectDetailsComments;
            
        }
        public ConfirmDetailsViewModel() { }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackCompleteController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    public class FeedbackCompleteController : Controller
    {
        [HttpGet("/feedback/complete/{feedbackId}")]
        public IActionResult Index(Guid feedbackId)
        {
            return View("~/Views/Feedback/Complete.cshtml");
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackConfirmDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.Feedback.AddAmmendmentComment;
using SFA.DAS.ASK.Application.Handlers.Feedback.GetVisitFeedback;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.ViewModels.Feedback;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    public class FeedbackConfirmDetailsController : Controller
    {
        private IMediator _mediator;

        public FeedbackConfirmDetailsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("feedback/confirm-details/{feedbackId}")]
        public async Task<IActionResult> Index(Guid feedbackId)
        {
            var details = await _mediator.Send(new GetVisitFeedbackRequest(feedbackId, true));

            if (details is null)
            {
                throw new SecurityException($"Feedback ID {feedbackId} is not valid.");
            }

            if (details.Status == FeedbackStatus.Complete)
            {
                return RedirectToAction("Index", "FeedbackComplete", new { feedbackId });
            }

            var vm = new ConfirmDetailsViewModel(details);

            return View("~/Views/Feedback/ConfirmDetails.cshtml", vm);
        }

        [HttpPost("feedback/confirm-details/{feedbackId}")]
        public async Task<IActionResult> StartFeedback(Guid feedbackId, ConfirmDetailsViewModel vm)
        {
            if (vm.IncorrectDetailsComments != null)
            {
                await _mediator.Send(new AddAmendmentCommentCommand(feedbackId, vm.IncorrectDetailsComments));
            }

            return RedirectToAction("Index", "FeedbackSection1", new { feedbackId = feedbackId });
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackSection1Controller.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/section1/")]
    public class FeedbackSection1Controller : FeedbackControllerBase<Section1ViewModel>
    {
        public FeedbackSection1Controller(IMediator mediator) : base(mediator)
        {
            ViewName = "~/Views/Feedback/Section1.cshtml";
            NextPageController = "FeedbackSection2";
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackSection2Controller.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/section2/")]
    public class FeedbackSection2Controller : FeedbackControllerBase<Section2ViewModel>
    {
        public FeedbackSection2Controller(IMediator mediator) : base(mediator)
        {
            ViewName = "~/Views/Feedback/Section2.cshtml";
            NextPageController = "FeedbackSection3";
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackSection3Controller.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/section3/")]
    public class FeedbackSection3Controller : FeedbackControllerBase<Section3ViewModel>
    {
        public FeedbackSection3Controller(IMediator mediator) : base(mediator)
        {
            ViewName = "~/Views/Feedback/Section3.cshtml";
            NextPageController = "FeedbackSection4";
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackSection4Controller.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/section4/")]
    public class FeedbackSection4Controller : FeedbackControllerBase<Section4ViewModel>
    {
        public FeedbackSection4Controller(IMediator mediator) : base(mediator)
        {
            ViewName = "~/Views/Feedback/Section4.cshtml";
            NextPageController = "FeedbackSection5";
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackSection5Controller.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/section5/")]
    public class FeedbackSection5Controller : FeedbackControllerBase<Section5ViewModel>
    {
        public FeedbackSection5Controller(IMediator mediator) : base(mediator)
        {
            ViewName = "~/Views/Feedback/Section5.cshtml";
            NextPageController = "FeedbackSection6";
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackSection6Controller.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/section6/")]
    public class FeedbackSection6Controller : FeedbackControllerBase<Section6ViewModel>
    {
        public FeedbackSection6Controller(IMediator mediator) : base(mediator)
        {
            ViewName = "~/Views/Feedback/Section6.cshtml";
            NextPageController = "FeedbackYourComments";
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackStartPageController.cs
using System;
using System.Security;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.Feedback.GetVisitFeedback;
using SFA.DAS.ASK.Application.Handlers.Feedback.StartFeedback;
using SFA.DAS.ASK.Data.Entities;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    public class FeedbackStartPageController : Controller
    {
        private readonly IMediator _mediator;

        public FeedbackStartPageController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("feedback/start/{feedbackId}")]
        public async Task<IActionResult> Index(Guid feedbackId)
        {
            var visitFeedback = await _mediator.Send(new GetVisitFeedbackRequest(feedbackId, true));
            if (visitFeedback is null)
            {
                throw new SecurityException($"Feedback ID {feedbackId} is not valid.");
            }

            if (visitFeedback.Status == FeedbackStatus.Complete)
            {
                return RedirectToAction("Index", "FeedbackComplete", new {feedbackId});
            }

            return await StartFeedback(feedbackId);
        }

        [HttpPost("feedback/start/{feedbackId}")]
        public async Task<IActionResult> StartFeedback(Guid feedbackId)
        {
            await _mediator.Send(new StartFeedbackCommand(feedbackId));

            return RedirectToAction("Index", "FeedbackConfirmDetails", new {feedbackId});
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/Feedback/FeedbackYourCommentsController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.Feedback.GetVisitFeedback;
using SFA.DAS.ASK.Application.Handlers.Feedback.SetVisitComplete;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels;

namespace SFA.DAS.ASK.Web.Controllers.Feedback
{
    [Route("feedback/your-comments/")]
    public class FeedbackYourCommentsController : FeedbackControllerBase<YourCommentsViewModel>
    {
        private readonly IMediator _mediator;

        public  FeedbackYourCommentsController(IMediator mediator) : base(mediator)
        {
            _mediator = mediator;
            ViewName = "~/Views/Feedback/YourComments.cshtml";
            NextPageController = "FeedbackComplete";
        }

        protected override async Task PostSubmitAction(Guid feedbackId)
        {
            var feedback = await _mediator.Send(new GetVisitFeedbackRequest(feedbackId, false));

            feedback.Status = FeedbackStatus.Complete;

            await _mediator.Send(new SetVisitFeedbackCompleteCommand(feedbackId, feedback.Status));
        }
    }
}

src/SFA.DAS.ASK.Web/Views/Feedback/Complete.cshtml
@{
    ViewBag.Title = "Feedback completed";
}

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                Thank you
            </h1>

            <div class="govuk-panel govuk-panel--confirmation">
                <h1 class="govuk-panel__title">
                    Feedback completed
                </h1>

                <div class="govuk-panel__body">
                    We have sent you a confirmation email
                </div>
            </div>
            <p></p>
            <h2 class="govuk-heading-m">What happens next</h2>
            <p class="govuk-body">
                Your feedback will be used to shape ASK activities in the future. You may be contacted to discuss some of your answers in more detail.
            </p>
            <p class="govuk-body">
                You can return to the <a href="https://fire-it-up-v18.herokuapp.com/campaign/hub-careers-advisers-V1" class="govuk-link--no-visited-state">Careers advice hub</a> to find apprenticeship resources and information for teachers and careers advisers.
            </p>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/ConfirmDetails.cshtml
@model SFA.DAS.ASK.Web.ViewModels.Feedback.ConfirmDetailsViewModel

@using SFA.DAS.ASK.Application.Utils;
@{
    ViewData["Title"] = "Confirm the details";
}

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                Confirm the details of your ASK visit
            </h1>

            <dl class="govuk-summary-list">
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key"> Establishment name </dt>
                    <dd class="govuk-summary-list__value"> @Model.EstablishmentName </dd>
                </div>
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key"> Your name </dt>
                    <dd class="govuk-summary-list__value"> @Model.YourFullName </dd>
                </div>
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key"> Date of the activity </dt>
                    <dd class="govuk-summary-list__value"> @Model.DateOfActivity </dd>
                </div>
            </dl>

            <h2 class="govuk-heading-m">The activities</h2>

            <dl class="govuk-summary-list">
                @foreach (var activity in Model.Activities)
                {
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"> Type of activity </dt>
                        <dd class="govuk-summary-list__value"> @EnumHelper.GetEnumDescription(@activity.ActivityType) </dd>
                    </div>
                }
            </dl>

            <form method="post">
                <details class="govuk-details" data-module="govuk-details">
                    <summary class="govuk-details__summary">
                        <span class="govuk-details__summary-text">
                            Is something incorrect?
                        </span>
                    </summary>
                    <div class="govuk-details__text">
                        <div class="govuk-form-group">
                            <label class="govuk-label" for="more-detail" id="more-detail-label">
                                Please describe which details are incorrect and why.
                            </label>

                            <textarea class="govuk-textarea" asp-for="IncorrectDetailsComments" rows="5" aria-describedby="more-detail-label"></textarea>
                        </div>
                    </div>

                </details>

                <button id="continueButton" class="govuk-button" asp-controller="FeedbackConfirmDetails" asp-action="StartFeedback" asp-route-feedbackId="@Model.FeedbackId" type="submit">Continue</button>

            </form>
            
            <a asp-action="Index" asp-controller="FeedbackStartPage" asp-route-feedbackId="@Model.FeedbackId" class="das-button--link">Cancel</a>

            <partial name="_DifficultiesFooter" />

        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/Section1.cshtml
@model SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels.Section1ViewModel

@{
    ViewBag.Title = "title";
}

<a asp-action="Index" asp-controller="FeedbackConfirmDetails" asp-route-feedbackId="@Model.FeedbackId" class="govuk-back-link">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                Please rate each part of the ASK support you received
                <span class="govuk-caption-xl">Section 1 of 7</span>
            </h1>
        </div>
    </div>

    <partial name="_ErrorSummary"/>
    
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            <form method="post">
                <partial name="_FeedbackRadios" for="InformationAndCommunicationBeforeVisit"/>
                <partial name="_FeedbackRadios" for="AskDeliveryPartnerWhoVisited"/>
                <partial name="_FeedbackRadios" for="ActivitiesDelivered"/>
                
                <button class="govuk-button" data-module="govuk-button">Continue</button>

                <a href="/feedback-form/index" class="das-button--link">Cancel</a>
            </form>
            <p class="govuk-hint">If you experience any difficulties in completing the form, please call for assistance on <a href="tel:01462 341191">01462 341191</a>.</p>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/Section2.cshtml
@model SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels.Section2ViewModel

@{
    ViewBag.Title = "title";
}

<a asp-action="Index" asp-controller="FeedbackSection1" asp-route-feedbackId="@Model.FeedbackId" class="govuk-back-link">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                How well did your ASK visit achieve each objective?
                <span class="govuk-caption-xl">Section 2 of 7</span>
            </h1>
        </div>
    </div>
    
    <partial name="_ErrorSummary"/>

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            <form method="post">
                <partial name="_FeedbackRadios" for="RaisingKnowledgeAndAwareness"/>
                <partial name="_FeedbackRadios" for="DemonstratingTheRangeAndOptions"/>
                <partial name="_FeedbackRadios" for="ExplainingApplicationAndRecruitmentProcess"/>

                <button class="govuk-button" data-module="govuk-button">Continue</button>

                <a href="/feedback-form/index" class="das-button--link">Cancel</a>
            </form>
            <p class="govuk-hint">If you experience any difficulties in completing the form, please call for assistance on <a href="tel:01462 341191">01462 341191</a>.</p>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/Section3.cshtml
@model SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels.Section3ViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<a asp-action="Index" asp-controller="FeedbackSection2" asp-route-feedbackId="@Model.FeedbackId" class="govuk-back-link">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                How well did your ASK visit achieve each objective?
                <span class="govuk-caption-xl">Section 3 of 7</span>
            </h1>
        </div>
    </div>

    <partial name="_ErrorSummary"/>
    
    <div class="govuk-grid-row">
            <div class="govuk-grid-column-full">
                <form method="post">
                    <partial name="_FeedbackRadios" for="DemonstratingDifferentTypesOfEmployers"/>
                    <partial name="_FeedbackRadios" for="IncreasingAwarenessOfHigherAndDegree"/>
                    <partial name="_FeedbackRadios" for="MakingStaffMoreConfident"/>
    
                    <button class="govuk-button" data-module="govuk-button">Continue</button>
    
                    <a href="/feedback-form/index" class="das-button--link">Cancel</a>
                </form>
                <p class="govuk-hint">If you experience any difficulties in completing the form, please call for assistance on <a href="tel:01462 341191">01462 341191</a>.</p>
            </div>
        </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/Section4.cshtml
@model SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels.Section4ViewModel

@{
    ViewBag.Title = "title";
}

<a asp-action="Index" asp-controller="FeedbackSection3" asp-route-feedbackId="@Model.FeedbackId" class="govuk-back-link">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                Did an apprentice or employer participate in this visit?
                <span class="govuk-caption-xl">Section 4 of 7</span>
            </h1>
        </div>
    </div>

    <partial name="_ErrorSummary"/>

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            <form method="post">

                <div class="govuk-form-group">
                    <fieldset class="govuk-fieldset">
                        <div class="govuk-radios govuk-radios--conditional" data-module="govuk-radios">
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" id="ApprenticeOrEmployerParticipateInVisit" asp-for="ApprenticeOrEmployerParticipateInVisit" type="radio" value="Yes" aria-controls="conditional-participation" aria-expanded="false">
                                <label class="govuk-label govuk-radios__label" for="ApprenticeOrEmployerParticipateInVisit">Yes</label>
                            </div>
                            <div class="govuk-radios__conditional govuk-radios__conditional--hidden" id="conditional-participation" sfa-gds-show-conditional-if-error-for="ApprenticeOrEmployerParticipationRating" show-conditional-if-model="ApprenticeOrEmployerParticipateInVisit" show-conditional-if-model-value="Yes">    
                                <partial name="_FeedbackRadios" for="ApprenticeOrEmployerParticipationRating"/>

                                <div class="govuk-form-group">
                                    <label class="govuk-label" for="participation-detail">
                                        Please add any other comments you have about their participation.
                                    </label>


                                    <textarea class="govuk-textarea" asp-for="ApprenticeOrEmployerParticipateComments" rows="5"></textarea>
                                </div>

                            </div>
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" id="ApprenticeOrEmployerParticipateInVisit_No" asp-for="ApprenticeOrEmployerParticipateInVisit" type="radio" value="No">
                                <label class="govuk-label govuk-radios__label" for="ApprenticeOrEmployerParticipateInVisit_No">No</label>
                            </div>
                        </div>
                    </fieldset>
                </div>


                <button class="govuk-button" data-module="govuk-button">Continue</button>

                <a href="/feedback-form/index" class="das-button--link">Cancel</a>
            </form>
            <p class="govuk-hint">If you experience any difficulties in completing the form, please call for assistance on <a href="tel:01462 341191">01462 341191</a>.</p>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/Section5.cshtml
@model SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels.Section5ViewModel  

@{
    ViewBag.Title = "title";
}

<a asp-action="Index" asp-controller="FeedbackSection4" asp-route-feedbackId="@Model.FeedbackId" class="govuk-back-link">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">
                Would you recommend ASK visits to other schools or educational establishments?
                <span class="govuk-caption-xl">Section 5 of 7</span>
            </h1>
        </div>
    </div>

    <partial name="_ErrorSummary"/>

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-full">
            <form method="post">

                <div class="govuk-form-group">
                    <fieldset class="govuk-fieldset">
                        <div class="govuk-radios govuk-radios--conditional" data-module="govuk-radios">
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" id="WouldYouRecommendAskVisits" asp-for="WouldYouRecommendAskVisits" type="radio" value="Yes">
                                <label class="govuk-label govuk-radios__label" for="WouldYouRecommendAskVisits">Yes</label>
                            </div>

                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" id="WouldYouRecommendAskVisits_No" asp-for="WouldYouRecommendAskVisits" type="radio" value="No" aria-controls="conditional-participation" aria-expanded="false">
                                <label class="govuk-label govuk-radios__label" for="WouldYouRecommendAskVisits_No">No</label>
                            </div>
                            <div class="govuk-radios__conditional govuk-radios__conditional--hidden" id="conditional-participation" sfa-gds-show-conditional-if-error-for="WouldNotRecommendAskVisitsComments" show-conditional-if-model="WouldYouRecommendAskVisits" show-conditional-if-model-value="No">
                                <div class="govuk-form-group" sfa-gds-error-class-for-name="WouldNotRecommendAskVisitsComments">
                                       
                                    <span id="has-sign-in-error" sfa-gds-error-message-for-name="WouldNotRecommendAskVisitsComments"></span>
        
                                    <label class="govuk-label" for="participation-detail">
                                        Why would you not recommend them?
                                    </label>

                                    <textarea class="govuk-textarea" asp-for="WouldNotRecommendAskVisitsComments" rows="5"></textarea>
                                </div>

                            </div>
                        </div>
                    </fieldset>
                </div>


                <button class="govuk-button" data-module="govuk-button">Continue</button>

                <a href="/feedback-form/index" class="das-button--link">Cancel</a>
            </form>
            <p class="govuk-hint">If you experience any difficulties in completing the form, please call for assistance on <a href="tel:01462 341191">01462 341191</a>.</p>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/Start.cshtml
@model Guid

@{
    ViewBag.Title = "Feedback";
}

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">Give feedback about your ASK visit</h1>
            <p class="govuk-body">You recently received apprenticeship support through the ASK programme, and we’d like to hear what you thought of it. Your feedback will help our ASK delivery partners to prepare and deliver future activities.</p>
            <p class="govuk-body">You’ll need to:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>confirm the details of the visit</li>
                <li>rate the service you received</li>
                <li>suggest any changes that could be made to future activities</li>
            </ul>
            <p class="govuk-body">This survey takes around <strong>5 minutes.</strong></p>
            <form method="post">
                <button type="submit" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
                    Start now
                    <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" role="presentation" focusable="false">
                        <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z"></path>
                    </svg>
                </button>
            </form>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/Feedback/YourComments.cshtml
@model SFA.DAS.ASK.Web.Controllers.Feedback.ViewModels.YourCommentsViewModel
@{
    ViewData["Title"] = "Your comments";
}

<a asp-action="Index" asp-controller="FeedbackSection6" asp-route-feedbackId="@Model.FeedbackId" class="govuk-back-link">Back</a>

<main class="govuk-main-wrapper" id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <h1 class="govuk-heading-xl">
                Your comments
                <span class="govuk-caption-xl">Section 7 of 7</span>
            </h1>

            <form method="post" asp-route-feedbackId="@Model.FeedbackId">
                <div class="govuk-form-group">
                    <label class="govuk-label" for=""> What were the best things about your ASK visit? </label>
                    <textarea class="govuk-textarea" asp-for="@Model.BestThingsAboutYourVisit" rows="5"></textarea>
                </div>

                <div class="govuk-form-group">
                    <label class="govuk-label" for=""> Was there anything that didn't work or could be improved? </label>
                    <textarea class="govuk-textarea" asp-for="@Model.WhatCouldBeImprovedAboutYourVisit" rows="5"></textarea>
                </div>

                <div class="govuk-form-group">
                    <label class="govuk-label" for=""> Please let us know any other comments you have </label>
                    <textarea class="govuk-textarea" asp-for="@Model.AddAnyOtherComments" rows="5"></textarea>
                </div>

                <button class="govuk-button" data-module="govuk-button" type="submit">
                    Submit feedback
                </button>
                <a asp-action="Index" asp-controller="FeedbackStartPage" asp-route-requestId="@Model.FeedbackId" class="das-button--link">Cancel</a>

            </form>
        </div>
    </div>
</main>