src/SFA.DAS.ASK.Web/ViewModels/DeliveryPartner/PlanningMeetings/CheckAnswersViewModel.cs
using SFA.DAS.ASK.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SFA.DAS.ASK.Web.ViewModels.DeliveryPartner.PlanningMeetings
{
    public class CheckAnswersViewModel
    {
        public Guid SupportId { get; set; }
        public Organisation Organisation { get; set; }
        public DateTime MeetingDateAndTime { get; set; }
        public MeetingType MeetingType { get; set; }
        public OrganisationContact OrganisationContact { get; set; }
        public Guid MyId { get; set; }

        public DeliveryPartnerContact DeliveryPartnerContact { get; set; }

        public CheckAnswersViewModel(SupportRequest request, PlanningMeeting meeting, OrganisationContact contact, DeliveryPartnerContact deliveryPartnerContact)
        {
            Organisation = request.Organisation;

            MeetingDateAndTime = meeting.MeetingTimeAndDate.Value;
            MeetingType = meeting.MeetingType.Value;
            OrganisationContact = contact;
            SupportId = request.Id;
            DeliveryPartnerContact = deliveryPartnerContact;
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/DeliveryPartnerAccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner
{
    public class DeliveryPartnerAccountController : Controller
    {
        [HttpGet("sign-out")]
        public IActionResult SignOut()
        {
            return SignOut(CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
        }
        
        [HttpGet]
        public IActionResult SignedOut()
        {
            return View();
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/DeliveryPartnerDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner
{
    [Route("delivery-partner/dashboard")]
    public class DeliveryPartnerDashboardController : Controller
    {
        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            return View("~/Views/DeliveryPartner/Dashboard/Dashboard.cshtml");
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/PlanningMeetings/CheckAnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetDeliveryPartnerContact;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetDeliveryPartnerContacts;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetOrCreatePlanningMeeting;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetOrganisationContacts;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetOrCreateOrganisationContact;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Web.ViewModels.DeliveryPartner.PlanningMeetings;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner.PlanningMeetings
{
    public class CheckAnswersController : Controller
    {
        private readonly IMediator _mediator;

        public CheckAnswersController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("delivery-partner/planning-meeting/check-answers/{supportId}")]
        [ImportModelState]
        public async Task<IActionResult> Index(Guid supportId)
        {
            //var myId = Guid.Parse("E9FDE3ED-8228-4A9F-9BF4-1516C06F1BD7");
            //var myOrgId = Guid.Parse("BB2D2212-7DA2-4DD9-9208-1C6715FB6216");

            var supportRequest = await _mediator.Send(new GetSupportRequest(supportId));
            var planningMeeting = await _mediator.Send(new GetPlanningMeetingRequest(supportId));
            var contacts = await _mediator.Send(new GetOrganisationContactsRequest(supportRequest.OrganisationId));
            var contact = contacts.Where(c => c.Id == supportRequest.OrganisationContactId).FirstOrDefault();
            var deliveryPartnerContact = await _mediator.Send(new GetDeliveryPartnerContactRequest(planningMeeting.DeliveryPartnerContactId.GetValueOrDefault()));

            var vm = new CheckAnswersViewModel(supportRequest, planningMeeting, contact, deliveryPartnerContact) ;

            return View("~/Views/DeliveryPartner/PlanningMeetings/CheckAnswers.cshtml", vm);
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/PlanningMeetings/DeliveryPartnerContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetDeliveryPartnerContacts;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetOrCreatePlanningMeeting;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.UpdatePlanningMeeting;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Services.Session;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Web.ViewModels.DeliveryPartner.PlanningMeetings;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner.PlanningMeetings
{
    public class DeliveryPartnerContactController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ISessionService _sessionService;

        public DeliveryPartnerContactController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }

        [HttpGet("delivery-partner/planning-meeting/delivery-partner-contact/{supportId}")]
        [ImportModelState]
        public async Task<IActionResult> Index(Guid supportId, bool edit)
        {
            //This will be retrieved from the sign in service or session service
            //var myId = Guid.Parse("CAC458E1-C88E-4E1D-9523-2FD1BB0F9EED");
            //var myOrgId = Guid.Parse("BB2D2212-7DA2-4DD9-9208-1C6715FB6216");
           
            //var signedInUser = _sessionService.Get<DeliveryPartnerContact>("SignedInContact");

            var supportRequest = await _mediator.Send(new GetSupportRequest(supportId));

            //if (supportRequest.DeliveryPartnerId != myOrgId)
            //{
            //    return RedirectToAction("Index", "DeliveryPartnerDashboard");
            //}

            var contacts = await _mediator.Send(new GetDeliveryPartnerContactsRequest(supportRequest.DeliveryPartnerId));
            var meeting = await _mediator.Send(new GetPlanningMeetingRequest(supportId));
           
            var viewModel = new DeliveryPartnerContactViewModel(contacts, meeting, supportRequest.DeliveryPartnerId, edit);

            return View("~/Views/DeliveryPartner/PlanningMeetings/DeliveryPartnerContact.cshtml", viewModel);
        }

        [HttpPost("delivery-partner/planning-meeting/delivery-partner-contact/{supportId}")]
        [ExportModelState]
        public async Task<IActionResult> Submit(Guid supportId, DeliveryPartnerContactViewModel viewModel)
        {
            if (viewModel.SelectedDeliveryPartnerContactId == Guid.Empty)
            {
                ModelState.AddModelError("SelectedDeliveryPartnerContactId", "Select an option");
              
                return RedirectToAction("Index", "DeliveryPartnerContact", new { supportId });
            }

            var planningMeeting = await _mediator.Send(new GetPlanningMeetingRequest(supportId));

            viewModel.UpdatePlanningMeeting(planningMeeting);

            await _mediator.Send(new UpdatePlanningMeetingCommand());

            if (viewModel.Edit)
            {
                return RedirectToAction("Index", "CheckAnswers", new { supportId });
            }

            return RedirectToAction("Index", "CheckAnswers", new { supportId });
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/PlanningMeetings/LogContactController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Handlers.Shared.UpdateSupportRequest;
using SFA.DAS.ASK.Application.Services.Session;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Web.ViewModels.DeliveryPartner.PlanningMeetings;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner.PlanningMeetings
{
    public class LogContactController : Controller
    {
        private IMediator _mediator { get; set; }
        private ISessionService _sessionService { get; set; }

        public LogContactController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }

        [HttpGet("delivery-partner/planning-meeting/log-contact/{supportId}")]
        [ImportModelState]
        public async Task<IActionResult> Index(Guid supportId)
        
        {
            var supportRequest = await _mediator.Send(new GetSupportRequest(supportId));
            
            if (supportRequest.CurrentStatus == Status.NewRequest)
            {
                var viewModel = new LogContactViewModel(supportRequest);

                return View("~/Views/DeliveryPartner/PlanningMeetings/Logcontact.cshtml", viewModel);
            }

            return RedirectToAction("Index", "DeliveryPartnerDashboard");
        }

        [HttpPost("delivery-partner/planning-meeting/log-contact/{supportId}")]
        [ExportModelState]
        public async Task<IActionResult> Index(Guid supportId, LogContactViewModel viewModel)
        {
            var supportRequest = await _mediator.Send(new GetSupportRequest(supportId));
            DateTime date;
            bool dateParsed = DateTime.TryParse($"{viewModel.Day}/{viewModel.Month}/{viewModel.Year}", out date);
            
            if (!dateParsed)
            { 
                ModelState.AddModelError("ContactedDate", "Enter a real date");
            }
           
            if (!ModelState.IsValid)
            {
                return View("~/Views/DeliveryPartner/PlanningMeetings/LogContact.cshtml", viewModel);
            }
            
            viewModel.UpdateSupportRequest(supportRequest);

            await _mediator.Send(new UpdateSupportRequestCommand());

            if (viewModel.SchedulePlanningMeeting == true)
            {
                return RedirectToAction("Index", "SchedulePlanningMeeting", new { supportId });
            }

            return RedirectToAction();
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/PlanningMeetings/PlanningContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetOrCreatePlanningMeeting;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.GetOrganisationContacts;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.PlanningMeetings.UpdatePlanningMeeting;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Handlers.Shared.CreateOrganisationContact;
using SFA.DAS.ASK.Application.Services.Session;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Web.ViewModels.DeliveryPartner.PlanningMeetings;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner.PlanningMeetings
{
    public class PlanningContactController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ISessionService _sessionService;

        public PlanningContactController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }

        [HttpGet("delivery-partner/planning-meeting/planning-contact/{supportId}")]
        [ImportModelState]
        public async Task<IActionResult> Index(Guid supportId, bool edit)
        {
            var supportRequest = await _mediator.Send(new GetSupportRequest(supportId));
            var planningMeeting = await _mediator.Send(new GetPlanningMeetingRequest(supportId));
            var contacts = await _mediator.Send(new GetOrganisationContactsRequest(supportRequest.OrganisationId));

            _sessionService.Set<List<OrganisationContact>>($"contacts-{supportId}", contacts);

            var vm = new PlanningContactViewModel(supportRequest, planningMeeting, contacts, edit) ;

            return View("~/Views/DeliveryPartner/PlanningMeetings/PlanningContact.cshtml", vm);
        
        }

        [HttpPost("delivery-partner/planning-meeting/planning-contact/{supportId}")]
        [ExportModelState]
        public async Task<IActionResult> Index(Guid supportId, PlanningContactViewModel vm)
        {
            if (vm.SelectedContact == Guid.Empty)
            {
                ValidateNewContact(vm);

                if (ModelState.ErrorCount > 1)
                {
                    vm.Contacts = _sessionService.Get<List<OrganisationContact>>($"contacts-{supportId}");
                    ModelState.AddModelError("SelectedContact", "Select an option");
                    return RedirectToAction("Index", "PlanningContact", new { supportId });
                }
                else
                {
                    await _mediator.Send(new CreateOrganisationContactCommand(Guid.NewGuid(), vm.NewFirstName, vm.NewLastName, vm.NewPhoneNumber,vm.NewEmail, vm.OrganisationId, "Not specified"));

                    return RedirectToAction("Index", "DeliveryPartnerContact", new { supportId = supportId });
                }
            }
            var planningMeeting = await _mediator.Send(new GetPlanningMeetingRequest(supportId));

            vm.UpdatePlanningMeeting(planningMeeting);

            await _mediator.Send(new UpdatePlanningMeetingCommand());

            if (vm.Edit)
            {
                return RedirectToAction("Index", "CheckAnswers", new { supportId });
            }

            return RedirectToAction("Index", "DeliveryPartnerContact", new { supportId = supportId });
        }

        private void ValidateNewContact(PlanningContactViewModel vm)
        {
            if (string.IsNullOrWhiteSpace(vm.NewFirstName))
            {
                ModelState.AddModelError("NewFirstName", "Please enter a first name");
            }
            if (string.IsNullOrWhiteSpace(vm.NewLastName))
            {
                ModelState.AddModelError("NewLastName", "Please enter a last name");
            }
            if (string.IsNullOrWhiteSpace(vm.NewPhoneNumber))
            {
                ModelState.AddModelError("NewPhoneNumber", "Please enter a phone number");
            }
            if (string.IsNullOrWhiteSpace(vm.NewEmail))
            {
                ModelState.AddModelError("NewEmail", "Please enter an email");
            }
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/DeliveryPartner/SupportRequestsController.cs
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.DeliveryPartner.GetSupportRequests;

namespace SFA.DAS.ASK.Web.Controllers.DeliveryPartner
{
    [Authorize]
    public class SupportRequestsController : Controller
    {
        private readonly IMediator _mediator;

        public SupportRequestsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("delivery-partner/support-requests/all")]
        public async Task<IActionResult> Index(SortBy sortBy)
        {
            return View("~/Views/DeliveryPartner/SupportRequests/SupportRequests.cshtml", await GetSupportRequests(sortBy));
        }

        [HttpGet("delivery-partner/support-requests/new")]
        public async Task<IActionResult> NewSupportRequests(SortBy sortBy)
        {
            return View("~/Views/DeliveryPartner/SupportRequests/NewSupportRequests.cshtml", await GetSupportRequests(sortBy));
        }
        
        [HttpGet("delivery-partner/support-requests/contacted")]
        public async Task<IActionResult> ContactedSupportRequests(SortBy sortBy)
        {   
            return View("~/Views/DeliveryPartner/SupportRequests/ContactedSupportRequests.cshtml", await GetSupportRequests(sortBy));
        }
        
        [HttpGet("delivery-partner/support-requests/contacted")]
        public async Task<IActionResult> RejectedSupportRequests(SortBy sortBy)
        {
            return View("~/Views/DeliveryPartner/SupportRequests/RejectedSupportRequests.cshtml", await GetSupportRequests(sortBy));
        }
        
        private async Task<SupportRequestsViewModel> GetSupportRequests(SortBy sortBy)
        {
            var supportRequests = await _mediator.Send(new GetSupportRequestsRequest());

            var supportRequestsViewModel = new SupportRequestsViewModel(supportRequests, sortBy);
            return supportRequestsViewModel;
        }
    }
}

src/SFA.DAS.ASK.Web/Views/DeliveryPartner/SupportRequests/ContactedSupportRequests.cshtml
@model SFA.DAS.ASK.Web.Controllers.DeliveryPartner.SupportRequestsViewModel

@{
    ViewBag.Title = "Support requests";
}

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing admin-page" id="main-content" role="main">


    <div class="govuk-grid-row" id="delivery-partner-dashboard">
        <div class="govuk-grid-column-full">
            <h1 class="govuk-heading-xl">
                Support requests
                <span class="govuk-caption-xl">Manage requests for ASK support</span>
            </h1>

            <div class="tabs request-tabs">
                 <div class="govuk-width-container">
                      <ul class="govuk-list">
                          <li>
                              <a asp-action="Index" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.AllSupportRequestsCount</span> - All requests</a>
                          </li>
                          <li>
                              <a asp-action="NewSupportRequests" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.NewSupportRequestsCount</span> - New requests</a>
                          </li>
                          <li>
                              <a asp-action="ContactedSupportRequests" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.ContactedSupportRequestsCount</span> - Contacted</a>
                          </li>
                          
                           <li><button class="govuk-link requests-rejected" onclick="openTab('tab-content-5')">Rejected</button></li>
                      </ul>
                 </div>
            </div>
            
           

            @if (Model.ContactedSupportRequests.Any())
            {
                <h2 class="govuk-heading-m sub-heading">Contacted</h2>
                @foreach (var sr in Model.ContactedSupportRequests)
                {
                    <div>
                        <div>
                            <span class="govuk-tag new">@sr.StatusDate</span>
                            <h2 class="govuk-heading-m">
                                @sr.OrganisationName
                                <span class="govuk-caption-m">
                                    @sr.OrganisationAddress
                                </span>
                            </h2>
                            <p class="govuk-body-m">
                                <span class="icon contact"></span> @sr.ContactName
                                <span class="icon telephone"></span> @sr.ContactTelephone
                                <span class="icon email"></span> <a href="mailto:@sr.ContactEmail">@sr.ContactEmail</a>
                            </p>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/DeliveryPartner/SupportRequests/NewSupportRequests.cshtml
@model SFA.DAS.ASK.Web.Controllers.DeliveryPartner.SupportRequestsViewModel

@{
    ViewBag.Title = "Support requests";
}

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing admin-page" id="main-content" role="main">


    <div class="govuk-grid-row" id="delivery-partner-dashboard">
        <div class="govuk-grid-column-full">
            <h1 class="govuk-heading-xl">
                Support requests
                <span class="govuk-caption-xl">Manage requests for ASK support</span>
            </h1>

            <div class="tabs request-tabs">
                <div class="govuk-width-container">
                    <ul class="govuk-list">
                        <li>
                            <a asp-action="Index" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.AllSupportRequestsCount</span> - All requests</a>
                        </li>
                        <li>
                            <a asp-action="NewSupportRequests" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.NewSupportRequestsCount</span> - New requests</a>
                        </li>
                        <li>
                            <a asp-action="ContactedSupportRequests" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.ContactedSupportRequestsCount</span> - Contacted</a>
                        </li>
                        <li>
                            <a class="govuk-link requests-all selected"><span class="number">@Model.RejectedSupportRequestsCount</span> - Rejected</a>
                        </li>
                    </ul>
                </div>
            </div>

            @if (Model.NewSupportRequests.Any())
            {
                <h2 class="govuk-heading-m sub-heading">New requests</h2>
                @foreach (var sr in Model.NewSupportRequests)
                {
                    <div>
                        <div>
                            @if (sr.StatusDate.Value.Date == DateTime.Today)
                            {
                                <span class="govuk-tag new">Today</span>
                            }
                            else if ((DateTime.Today.Date - sr.StatusDate.Value.Date).Days < 3)
                            {
                                var daysOld = (DateTime.Today.Date - sr.StatusDate.Value.Date).Days;
                                if (daysOld == 1)
                                {
                                    <span class="govuk-tag new">@daysOld day old</span>
                                }
                                else
                                {
                                    <span class="govuk-tag new">@daysOld days old</span>
                                }
                            }
                            else if ((DateTime.Today.Date - sr.StatusDate.Value.Date).Days < 6)
                            {
                                var daysOld = (DateTime.Today.Date - sr.StatusDate.Value.Date).Days;

                                <span class="govuk-tag lapsed">@daysOld days old</span>
                            }
                            else
                            {
                                var daysOld = (DateTime.Today.Date - sr.StatusDate.Value.Date).Days;

                                <span class="govuk-tag rejected">@daysOld days old</span>
                            }


                            <h2 class="govuk-heading-m">
                                @sr.OrganisationName
                                <span class="govuk-caption-m">
                                    @sr.OrganisationAddress
                                </span>
                            </h2>
                            <p class="govuk-body-m">
                                <span class="icon contact"></span> @sr.ContactName
                                <span class="icon telephone"></span> @sr.ContactTelephone
                                <span class="icon email"></span> <a href="mailto:@sr.ContactEmail">@sr.ContactEmail</a>
                            </p>
                        </div>
                        <div class="cta-wrapper">

                        </div>
                    </div>
                }
            }
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/DeliveryPartner/SupportRequests/RejectedSupportRequests.cshtml
@model SFA.DAS.ASK.Web.Controllers.DeliveryPartner.SupportRequestsViewModel

@{
    ViewBag.Title = "Rejected Support requests";
}

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing admin-page" id="main-content" role="main">


    <div class="govuk-grid-row" id="delivery-partner-dashboard">
        <div class="govuk-grid-column-full">
            <h1 class="govuk-heading-xl">
                Support requests
                <span class="govuk-caption-xl">Manage requests for ASK support</span>
            </h1>

            <div class="tabs request-tabs">
                 <div class="govuk-width-container">
                      <ul class="govuk-list">
                          <li>
                              <a asp-action="Index" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.AllSupportRequestsCount</span> - All requests</a>
                          </li>
                          <li>
                              <a asp-action="NewSupportRequests" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.NewSupportRequestsCount</span> - New requests</a>
                          </li>
                          <li>
                              <a asp-action="ContactedSupportRequests" asp-controller="SupportRequests" class="govuk-link requests-all selected"><span class="number">@Model.ContactedSupportRequestsCount</span> - Contacted</a>
                          </li>
                          
                           <li><button class="govuk-link requests-rejected" onclick="openTab('tab-content-5')">Rejected</button></li>
                      </ul>
                 </div>
            </div>
            
           

            @if (Model.ContactedSupportRequests.Any())
            {
                <h2 class="govuk-heading-m sub-heading">Rejected</h2>
                @foreach (var sr in Model.ContactedSupportRequests)
                {
                    <div>
                        <div>
                            <span class="govuk-tag new">@sr.StatusDate</span>
                            <h2 class="govuk-heading-m">
                                @sr.OrganisationName
                                <span class="govuk-caption-m">
                                    @sr.OrganisationAddress
                                </span>
                            </h2>
                            <p class="govuk-body-m">
                                <span class="icon contact"></span> @sr.ContactName
                                <span class="icon telephone"></span> @sr.ContactTelephone
                                <span class="icon email"></span> <a href="mailto:@sr.ContactEmail">@sr.ContactEmail</a>
                            </p>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</main>