src/SFA.DAS.ASK.Web/Controllers/RequestSupport/ApplicationCompleteController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class ApplicationCompleteController : Controller
    {
        private readonly IMediator _mediator;

        public ApplicationCompleteController(IMediator mediator)
        {
            _mediator = mediator;
        }
        
        [HttpGet("application-complete/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId)
        {
            var supportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));
            
            var vm = new ApplicationCompleteViewModel(){Email = supportRequest.Email};
            return View("~/Views/RequestSupport/ApplicationComplete.cshtml", vm);
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/CancelSupportRequestController.cs
using System;
using System.Composition;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.CancelSupportRequest;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class CancelSupportRequestController : Controller
    {
        private readonly IMediator _mediator;
        
        public CancelSupportRequestController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("cancel-request/{requestId}")]
        [ImportModelState]
        public  IActionResult Index(Guid requestId, string returnAction, string returnController)
        {
            var vm = new CancelSupportRequestViewModel(requestId, returnAction, returnController);
            
            return View("~/Views/RequestSupport/CancelRequest.cshtml", vm);
        }
        
        [HttpPost("cancel-request/{requestId}")]
        [ExportModelState]
        public async Task<IActionResult> Cancel(Guid requestId, CancelSupportRequestViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", new {requestId, vm.ReturnAction, vm.ReturnController});
            }

            if (!vm.ConfirmedCancel.Value)
            {
                return RedirectToAction(vm.ReturnAction, vm.ReturnController, new {requestId = requestId});
            }

            await _mediator.Send(new CancelSupportRequestCommand(requestId));
            return RedirectToAction("Index", "Home");

        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/CheckYourDetailsController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Services.Session;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.Infrastructure.Filters;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class CheckYourDetailsController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ISessionService _sessionService;

        public CheckYourDetailsController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }

        [HttpGet("check-your-details/{requestId}")]
        [ServiceFilter(typeof(CheckRequestFilter))]
        public async Task<IActionResult> Index(Guid requestId)
        {
            var tempSupportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));
            var numberOfOrgs = _sessionService.Get("NumberOfOrgs");
            var searchTerms = _sessionService.Get($"Searchstring-{requestId}");

            var vm = new CheckYourDetailsViewModel(tempSupportRequest, numberOfOrgs, searchTerms);

            return View("~/Views/RequestSupport/CheckYourDetails.cshtml", vm);
        }

        [HttpPost("check-your-details/{requestId}")]
        public IActionResult Continue(Guid requestId)
        {
            return RedirectToAction("Index", "OtherDetails", new {requestId});
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/HasSignInController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.StartTempSupportRequest;
using SFA.DAS.ASK.Application.Services.Session;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class HasSignInController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ISessionService _sessionService;

        public HasSignInController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }
        
        [HttpGet("has-signin")]
        [ImportModelState]
        public async Task<IActionResult> Index()
        {
            return await Index(new HasSignInViewModel() {HasSignInAccount = false});

            // var vm = new HasSignInViewModel();
            // var hasSignIn = _sessionService.Get("HasSignIn");
            // if (hasSignIn != null)
            // {
            //     vm.HasSignInAccount = bool.Parse(hasSignIn);
            // }
            //
            // return View("~/Views/RequestSupport/HasSignIn.cshtml", vm);
        }

        [HttpPost("has-signin")]
        [ExportModelState]
        public async Task<IActionResult> Index(HasSignInViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            
            _sessionService.Set("HasSignIn", viewModel.HasSignInAccount.GetValueOrDefault().ToString());
            
            if (viewModel.HasSignInAccount.GetValueOrDefault())
            {
                return RedirectToAction("SignIn", "RequestSupportSignIn");
            }

            var cachedRequestIdString = _sessionService.Get("TempSupportRequestId");
            var requestId = cachedRequestIdString == null
                ? (await _mediator.Send(new StartTempSupportRequestCommand(SupportRequestType.Manual))).RequestId
                : Guid.Parse(cachedRequestIdString);

            _sessionService.Set("TempSupportRequestId", requestId.ToString());
            
            return RedirectToAction("Index", "YourDetails", new {requestId = requestId});
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/HomeController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.StartTempSupportRequest;
using SFA.DAS.ASK.Application.Services.Session;
using SFA.DAS.ASK.Web.Models;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class HomeController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ISessionService _sessionService;

        public HomeController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> NewRequest()
        {
            var requestId = (await _mediator.Send(new StartTempSupportRequestCommand())).RequestId;

            _sessionService.Set("TempSupportRequestId", requestId.ToString());

            return RedirectToAction("Index", "YourDetails", new { requestId = requestId});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/InvalidLocationController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class InvalidLocationController : Controller
    {
        public IActionResult Index(Guid requestid)
        {
            return View("~/Views/RequestSupport/InvalidLocation.cshtml", requestid);
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/OrganisationDetailsController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.SaveSupportRequest;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class OrganisationDetailsController : Controller
    {
        private readonly IMediator _mediator;

        public OrganisationDetailsController(IMediator mediator)
        {
            _mediator = mediator;
        }
        
        [HttpGet("organisation-details/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId)
        {
            var supportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));
            
            var vm = new OrganisationDetailsViewModel(supportRequest);

            return View("~/Views/RequestSupport/OrganisationDetails.cshtml", vm);
        }

        [HttpPost("organisation-details/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId, OrganisationDetailsViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("~/Views/RequestSupport/OrganisationDetails.cshtml", viewModel);
            }

            if (viewModel.SelectedOrganisationType == OrganisationType.Other && string.IsNullOrWhiteSpace(viewModel.Other))
            {
                ModelState.AddModelError("organisationType_other_details", "Please enter something for Other");
                return View("~/Views/RequestSupport/OrganisationDetails.cshtml", viewModel);
            }
            
            var supportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));
            
            await _mediator.Send(new SaveTempSupportRequest(viewModel.ToSupportRequest(supportRequest)));

            // if (viewModel.SelectedOrganisationType == OrganisationType.School) // School
            // {
            //     //return RedirectToAction("Index", "SchoolDetails", new {requestId = requestId});
            // }
            
            return RedirectToAction("Index", "OrganisationSearch", new {requestId = requestId});
            //return Ok();
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/OrganisationResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MediatR;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetNonDfeOrganisations;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.AddNonDfeSignInInformation;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;
using SFA.DAS.ASK.Application.Services.Session;
using Newtonsoft.Json;
using SFA.DAS.ASK.Application.Services.ReferenceData;
using System.Threading;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.CheckOrganisationLocation;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSelectedOrganisationSearchResult;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class OrganisationResultsController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ISessionService _sessionService;

        public OrganisationResultsController(IMediator mediator, ISessionService sessionService)
        {
            _mediator = mediator;
            _sessionService = sessionService;
        }

        [HttpGet("organisation-results/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId, string search, bool edit)
        {
            var supportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));

            var results = (await _mediator.Send(new GetNonDfeOrganisationsRequest(search, requestId), default(CancellationToken))).ToList();

            var viewModel = new OrganisationResultsViewModel(results, requestId, search, edit, supportRequest.ReferenceId);

            return View("~/Views/RequestSupport/OrganisationResults.cshtml", viewModel);
        }

        [HttpPost("organisation-results/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId, OrganisationResultsViewModel viewModel)
        {
            var selectedResult = await _mediator.Send(new GetSelectedOrganisationSearchResultRequest(viewModel.SelectedResult, requestId));

            if (string.IsNullOrWhiteSpace(selectedResult.Address.Postcode) || !(await _mediator.Send(new CheckOrganisationLocationRequest(selectedResult.Address.Postcode))))
            {
                return RedirectToAction("Index", "InvalidLocation", new {requestId});
            }
            
            await _mediator.Send(new AddNonDfESignInInformationCommand(selectedResult, requestId));

            return RedirectToAction("Index", "CheckYourDetails", new { requestId = requestId, search = viewModel.Search });
        }

    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/OrganisationSearchController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;
using MediatR;
using System.Threading.Tasks;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetNonDfeOrganisations;
using SFA.DAS.ASK.Application.Services.DfeApi;
using System.Collections.Generic;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Web.Infrastructure.ModelStateTransfer;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class OrganisationSearchController : Controller
    {
        private readonly IMediator _mediator;

        public OrganisationSearchController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [HttpGet("organisation-search/{requestId}")]
        [ImportModelState]
        public async Task<IActionResult> Index(Guid requestId, string search)
        {
            var tempSupportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));
            var vm = new OrganisationSearchViewModel(tempSupportRequest, search);
            return View("~/Views/RequestSupport/OrganisationSearch.cshtml", vm);
        }

        [HttpPost("organisation-search/{requestId}")]
        [ExportModelState]
        public IActionResult Search(Guid requestId, OrganisationSearchViewModel viewmodel)
        {
            return !ModelState.IsValid 
                ? RedirectToAction("Index", "OrganisationSearch", new { requestId = requestId }) 
                : RedirectToAction("Index", "OrganisationResults", new { requestId = requestId, search = viewmodel.Search });
        }
    }
}

src/SFA.DAS.ASK.Web/Controllers/RequestSupport/OrganisationTypeController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.GetSupportRequest;
using SFA.DAS.ASK.Application.Handlers.RequestSupport.SaveSupportRequest;
using SFA.DAS.ASK.Data.Entities;
using SFA.DAS.ASK.Web.ViewModels.RequestSupport;

namespace SFA.DAS.ASK.Web.Controllers.RequestSupport
{
    public class OrganisationTypeController : Controller
    {
        private readonly IMediator _mediator;

        public OrganisationTypeController(IMediator mediator)
        {
            _mediator = mediator;
        }
        
        [HttpGet("organisation-type/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId)
        
        {
            var supportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));
            
            var vm = new OrganisationTypeViewModel(supportRequest);

            return View("~/Views/RequestSupport/OrganisationType.cshtml", vm);
        }

        [HttpPost("organisation-type/{requestId}")]
        public async Task<IActionResult> Index(Guid requestId, OrganisationTypeViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("~/Views/RequestSupport/OrganisationType.cshtml", viewModel);
            }

            if (viewModel.SelectedOrganisationType == OrganisationType.Other && string.IsNullOrWhiteSpace(viewModel.Other))
            {
                ModelState.AddModelError("Other", "Please enter something for other");
                return View("~/Views/RequestSupport/OrganisationType.cshtml", viewModel);
            }
            
            var supportRequest = await _mediator.Send(new GetTempSupportRequest(requestId));

            viewModel.UpdateTempSupportRequest(supportRequest);

            await _mediator.Send(new SaveTempSupportRequest());
           
            return RedirectToAction("Index", "OrganisationSearch", new {requestId = requestId});
        }
    }
}

src/SFA.DAS.ASK.Web/Views/RequestSupport/ApplicationComplete.cshtml
@model SFA.DAS.ASK.Web.ViewModels.RequestSupport.ApplicationCompleteViewModel

@{
    ViewBag.Title = "Application complete";
}
<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <div class="govuk-panel govuk-panel--confirmation">
                <h1 class="govuk-panel__title">
                    Application complete
                </h1>

                <div class="govuk-panel__body">
                    We have sent you a confirmation email
                </div>
            </div>
           
            <h2 class="govuk-heading-m">What happens next</h2>
            <p class="govuk-body">
                A local ASK delivery partner will get in touch with you. They'll set up a planning meeting to discuss
                your needs and choose the most suitable support options available through the ASK programme.
            </p>
            <p class="govuk-body">
                In the meantime, you can return to the
                <a href="https://fire-it-up-v18.herokuapp.com/campaign/hub-careers-advisers-V1" class="govuk-link--no-visited-state">Careers advice hub</a>
                to find apprenticeship resources and information for teachers and careers advisers.
            </p>
            @* <p class="govuk-body"> *@
            @*     <a href="#" class="govuk-link">What did you think of this service?</a> (takes 30 seconds) *@
            @* </p> *@
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/RequestSupport/CancelRequest.cshtml
@model SFA.DAS.ASK.Web.ViewModels.RequestSupport.CancelSupportRequestViewModel

@{
    ViewBag.Title = "Select organisation";
}
<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">


            <partial name="_ErrorSummary"/>

            <form method="post">

                <input type="hidden" asp-for="ReturnAction"/>
                <input type="hidden" asp-for="ReturnController"/>

                <div class="govuk-form-group" sfa-gds-error-class-for="ConfirmedCancel">
                    <fieldset class="govuk-fieldset">
                        <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">

                            <h1 class="govuk-fieldset__heading">
                                Are you sure you want to cancel your support request?
                            </h1>

                        </legend>
                        <span id="changed-name-hint" class="govuk-hint">
                            This will remove the information you've entered so far.
                        </span>


                        <span sfa-gds-error-message-for="ConfirmedCancel"></span>

                        <div class="govuk-radios">
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" type="radio" asp-for="ConfirmedCancel" id="HasSignInAccount" value="true">
                                <label class="govuk-label govuk-radios__label" for="HasSignInAccount">
                                    Yes, cancel my support request
                                </label>
                            </div>

                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" type="radio" asp-for="ConfirmedCancel" id="hasSignInAccount_No" value="false">
                                <label class="govuk-label govuk-radios__label" for="hasSignInAccount_No">
                                    No, go back to my support request
                                </label>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <button id="continueButton" class="govuk-button" data-module="govuk-button" type="submit">
                    Confirm
                </button>
            </form>
            <partial name="_DifficultiesFooter"/>


            @* <form method="post" asp-action="Cancel" asp-controller="CancelSupportRequest" asp-route-requestId="@Model.RequestId"> *@
            @*     <button class="govuk-button" data-module="govuk-button" type="submit"> *@
            @*         Yes *@
            @*     </button> *@
            @*     <a id="cancelLink" asp-action="@Model.ReturnAction" asp-controller="@Model.ReturnController" asp-route-requestId="@Model.RequestId" class="govuk-link cancel-link">No</a> *@
            @* </form> *@

        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/RequestSupport/CheckYourDetails.cshtml
@using SFA.DAS.ASK.Application.Handlers.RequestSupport.DfeOrganisationsCheck
@using SFA.DAS.ASK.Data.Entities
@model SFA.DAS.ASK.Web.ViewModels.RequestSupport.CheckYourDetailsViewModel

@{
    ViewBag.Title = "Check your details";
}
@if (Model.SupportRequestType == SupportRequestType.DfeSignIn)
{
    if (Model.NumberOfOrgs == DfeOrganisationCheckResult.Single)
    {
        <a asp-action="Index" asp-controller="HasSignIn" class="govuk-back-link">Back</a>
    }
    else if (Model.NumberOfOrgs == DfeOrganisationCheckResult.None)
    {
        <a asp-action="Index" asp-controller="OrganisationResults" asp-route-requestId="@Model.RequestId" class="govuk-back-link">Back</a>
    }
    else
    {
        <a asp-action="Index" asp-controller="SelectOrganisation" asp-route-requestId="@Model.RequestId" class="govuk-back-link">Back</a>
    }
}
else
{
    <a asp-action="Index" asp-controller="OrganisationResults" asp-route-requestId="@Model.RequestId" asp-route-search="@Model.SearchTerm" class="govuk-back-link">Back</a>
}

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">Check your details</h1>

            <h2 class="govuk-heading-m">Your details</h2>
            <dl class="govuk-summary-list">
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Name
                    </dt>
                    <dd class="govuk-summary-list__value">
                        @Model.Name
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        <a asp-action="Index" asp-controller="YourDetails" asp-route-requestId="@Model.RequestId" asp-route-edit="true" class="govuk-link">Change</a>
                    </dd>
                </div>

                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Contact details
                    </dt>
                    <dd class="govuk-summary-list__value">
                        @Model.PhoneNumber <br/>
                        @Model.Email <br/>
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        <a asp-action="Index" asp-controller="YourDetails" asp-route-requestId="@Model.RequestId" asp-route-edit="true" class="govuk-link">Change</a>
                    </dd>
                </div>
            </dl>

            <h2 class="govuk-heading-m">Organisation details</h2>
            <dl class="govuk-summary-list">
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Name
                    </dt>
                    <dd class="govuk-summary-list__value">
                        <strong>
                            @Model.OrganisationName
                        </strong>
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        @if (Model.SupportRequestType == SupportRequestType.Manual)
                        {
                            <a asp-action="Index" asp-controller="OrganisationResults" asp-route-requestId="@Model.RequestId" asp-route-search="@Model.SearchTerm" asp-route-edit="true" class="govuk-link">Change</a>
                        }
                        else if (Model.NumberOfOrgs == DfeOrganisationCheckResult.Multiple)
                        {
                            <a asp-action="Index" asp-controller="SelectOrganisation" asp-route-requestId="@Model.RequestId" asp-route-edit="true" class="govuk-link">Change</a>
                        }
                    </dd>
                </div>
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Address
                    </dt>
                    <dd class="govuk-summary-list__value">
                        @Model.BuildingAndStreet1 <br/>
                        @Model.BuildingAndStreet2 <br/>
                        @Model.TownOrCity <br/>
                        @Model.County <br/>
                        @Model.Postcode <br/>
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        @if (Model.SupportRequestType == SupportRequestType.Manual)
                        {
                            <a asp-action="Index" asp-controller="OrganisationResults" asp-route-requestId="@Model.RequestId" asp-route-search="@Model.SearchTerm" asp-route-edit="true" class="govuk-link">Change</a>
                        }
                        else if (Model.NumberOfOrgs == DfeOrganisationCheckResult.Multiple)
                        {
                            <a asp-action="Index" asp-controller="SelectOrganisation" asp-route-requestId="@Model.RequestId" asp-route-edit="true" class="govuk-link">Change</a>
                        }
                    </dd>
                </div>
            </dl>

            <form method="post" asp-action="Index" asp>
                <button id="continueButton" class="govuk-button" data-module="govuk-button" type="submit">
                    Continue
                </button>
                <a id="cancelLink" asp-action="Index" asp-controller="CancelSupportRequest" asp-route-requestId="@Model.RequestId" asp-route-returnAction="Index" asp-route-returnController="CheckYourDetails" class="das-button--link">Cancel</a>
            </form>
            <partial name="_DifficultiesFooter"/>
        </div>
    </div>
</main>

src/SFA.DAS.ASK.Web/Views/RequestSupport/OrganisationSearch.cshtml
@model SFA.DAS.ASK.Web.ViewModels.RequestSupport.OrganisationSearchViewModel

@{
    ViewBag.Title = "Organisation search";
}

<a class="govuk-back-link" asp-action="Index" asp-controller="OrganisationType" asp-route-requestId="@Model.RequestId">Back</a>

<main class="govuk-main-wrapper " id="main-content" role="main">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <partial name="_ErrorSummary" />

            <h1 class="govuk-heading-xl">
                Search for @Model.OrganisationType
            </h1>

            <form method="post" asp-action="Search" asp-controller="OrganisationSearch" asp-route-requestId="@Model.RequestId">


                <div class="govuk-form-group" sfa-gds-error-class-for="Search">
                    <label class="govuk-label" for="Search">Search term</label>
                    <span id="organisation-search-error" sfa-gds-error-message-for="Search"></span>
                    <input class="govuk-input" asp-for="Search" type="text" aria-describedby="organisation-search-error">
                </div>

                <button class="govuk-button" data-module="govuk-button" type="submit">
                    Search
                </button>

                <a asp-action="Index" asp-controller="CancelSupportRequest" asp-route-requestId="@Model.RequestId" asp-route-returnAction="Index" asp-route-returnController="OrganisationSearch" class="das-button--link">Cancel</a>

            </form>
            <partial name="_DifficultiesFooter" />
        </div>
    </div>
</main>